---
framework: mocha                  # Mention the testing framework mocha or jest
postMerge:
    pattern:
    - "./**/*.js"            # Glob pattern to path where tests that should run post-merge are written
preMerge:
    - "./**/*.js"              # Glob pattern to path where tests that should run pre-merge are written
preRun:
    - npm i                   # Mention pre-run steps here
postRun:
    - node --version                # Mention post-run steps here
configFile: ".tas.mocharc.json"   # Mention config file if any
version: 2.0