---
framework: "jest"
blocklist:
  - "jest-tests/alibaba.spec.js##Alibaba Search##shows search results after search input"
postMerge:
  pattern:
    - "./jest-tests/*.js"
preMerge:
  pattern:
    - "./jest-tests/*.js"
preRun:
  - npm i
postRun:
  - node --version
version: 2.0
